Repository DeveloperAcademy-POSTECH/MC3-Team2-APillog, pull requests merged in 2022-07, with the labels that each got.

#9 [Feat] 데이터 모델 추가
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/APillLog.xcdatamodeld/APillLog.xcdatamodel/contents
  APillLog/APillLog/Assets.xcassets/AppIcon.appiconset/Contents.json
  APillLog/Condition+CoreDataClass.swift
  APillLog/Condition+CoreDataProperties.swift
  APillLog/History+CoreDataClass.swift
  APillLog/History+CoreDataProperties.swift
Labels: enhancement

#16 [Feat] File Structure 구성 및 탭바에 각 뷰 연결
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/Application/AppDelegate.swift
  APillLog/APillLog/Application/SceneDelegate.swift
  APillLog/APillLog/Base.lproj/Main.storyboard
  APillLog/APillLog/CoreData/APillLog.xcdatamodeld/.xccurrentversion
  APillLog/APillLog/CoreData/APillLog.xcdatamodeld/APillLog.xcdatamodel/contents
  APillLog/APillLog/CoreData/Condition+CoreDataClass.swift
  APillLog/APillLog/CoreData/Condition+CoreDataProperties.swift
  APillLog/APillLog/CoreData/History+CoreDataClass.swift
  APillLog/APillLog/CoreData/History+CoreDataProperties.swift
  APillLog/APillLog/Extentions/APillLog+Color.swift
  APillLog/APillLog/Extentions/APillLog+Font.swift
  APillLog/APillLog/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  APillLog/APillLog/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  APillLog/APillLog/Resources/Assets.xcassets/Contents.json
  APillLog/APillLog/Utility/Fonts/AppleSDGothicNeoB.ttf
  APillLog/APillLog/Utility/Fonts/AppleSDGothicNeoEB.ttf
  APillLog/APillLog/Utility/Fonts/AppleSDGothicNeoH.ttf
  APillLog/APillLog/Utility/Fonts/AppleSDGothicNeoL.ttf
  APillLog/APillLog/Utility/Fonts/AppleSDGothicNeoM.ttf
  APillLog/APillLog/Utility/Fonts/AppleSDGothicNeoR.ttf
  APillLog/APillLog/Utility/Fonts/AppleSDGothicNeoSB.ttf
  APillLog/APillLog/Utility/Fonts/AppleSDGothicNeoT.ttf
  APillLog/APillLog/Utility/Fonts/AppleSDGothicNeoUL.ttf
  APillLog/APillLog/View/Base.lproj/LaunchScreen.storyboard
  APillLog/APillLog/View/Base.lproj/Main.storyboard
  APillLog/APillLog/View/DiaryTab/DiaryView.storyboard
  APillLog/APillLog/View/DiaryTab/DiaryViewController.swift
  APillLog/APillLog/View/HistoryTab/HistoryView.storyboard
  APillLog/APillLog/View/HistoryTab/HistoryViewController.swift
  APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
  APillLog/APillLog/ViewController.swift
Labels: enhancement

#28 [Feat] #15 - 서브약 추가 뷰 추가
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/View/Base.lproj/Main.storyboard
  APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
  APillLog/APillLog/View/MedicationTab/SecondaryPill/AddSecondaryPillView.storyboard
  APillLog/APillLog/View/MedicationTab/SecondaryPill/AddSecondaryPillViewController.swift
Labels: enhancement, 💡 LED

#31 [Feat] #13 - 메인 약 추가 뷰 Layout 구현
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPill.storyboard
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/PrimaryPillDosingCycleChipButton.swift
  APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
Labels: enhancement, 🐧 Jun

#36 [Feat] #6 History view UI 구현
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/View/HistoryTab/HistoryTableViewCell.swift
  APillLog/APillLog/View/HistoryTab/HistoryTableViewCell.xib
  APillLog/APillLog/View/HistoryTab/HistoryView.storyboard
  APillLog/APillLog/View/HistoryTab/HistoryViewController.swift
Labels: enhancement, 🍔 Soi

#34 [Feat] CoreData 함수 추가
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/CoreData/APillLog.xcdatamodeld/APillLog.xcdatamodel/contents
  APillLog/APillLog/CoreData/CoreDataManager.swift
  APillLog/APillLog/CoreData/History+CoreDataClass.swift
  APillLog/APillLog/CoreData/History+CoreDataProperties.swift
  APillLog/APillLog/View/DiaryTab/DiaryView.storyboard
  APillLog/APillLog/View/DiaryTab/DiaryViewController.swift
Labels: enhancement

#44 [Feat] #27 - 메인약 추가뷰에서 코어데이터연결
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPill.storyboard
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift
Labels: enhancement, ⚡️ Cookie, 🐧 Jun

#43 [Feat] #39 - HistoryView에 Coredata 연결
  APillLog/APillLog/View/HistoryTab/HistoryTableViewCell.xib
  APillLog/APillLog/View/HistoryTab/HistoryView.storyboard
  APillLog/APillLog/View/HistoryTab/HistoryViewController.swift
Labels: enhancement, 🍔 Soi

#46 [Feat] #23 - Date picker 구현 및 뷰와 연결
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/Utility/Calendar/CalendarView.swift
  APillLog/APillLog/Utility/Calendar/CalendarView.xib
  APillLog/APillLog/View/HistoryTab/HistoryView.storyboard
  APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
Labels: enhancement, 🍔 Soi

#47 [Feat] DiaryView 구현
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/View/Base.lproj/Main.storyboard
  APillLog/APillLog/View/DiaryTab/CustomCellTableViewCell.swift
  APillLog/APillLog/View/DiaryTab/DiaryView.storyboard
  APillLog/APillLog/View/DiaryTab/DiaryViewController.swift
  APillLog/APillLog/View/DiaryTab/DiaryWriteViewController.swift
  APillLog/APillLog/View/DiaryTab/MyCustomHeader.swift
Labels: enhancement, 👀 Dodo

#49 [Feat] #37 - MedicationView - ManageDosingView - AddPrimaryPillView 연결
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/CoreData/CoreDataManager.swift
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPill.storyboard
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift
  APillLog/APillLog/View/MedicationTab/AddSecondaryPillView/AddSecondaryPillView.storyboard
  APillLog/APillLog/View/MedicationTab/AddSecondaryPillView/AddSecondaryPillViewController.swift
  APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingView.storyboard
  APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingViewController.swift
  APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
Labels: enhancement, 💡 LED

#51 [Feat] #37 - 메인약 복용 뷰 구현
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/CoreData/CoreDataManager.swift
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPill.storyboard
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift
  APillLog/APillLog/View/MedicationTab/AddSecondaryPillView/AddSecondaryPillView.storyboard
  APillLog/APillLog/View/MedicationTab/AddSecondaryPillView/AddSecondaryPillViewController.swift
  APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingView.storyboard
  APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingViewController.swift
  APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
Labels: enhancement, 💡 LED

#53 [Feat] #45 - 증상 기록 화면 구현
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/Extentions/APillLog+Color.swift
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPill.storyboard
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/PrimaryPillDosingCycleChipButton.swift
  APillLog/APillLog/View/MedicationTab/CheckCondition/CheckConditionView.storyboard
  APillLog/APillLog/View/MedicationTab/CheckCondition/CheckConditionViewController.swift
  APillLog/APillLog/View/MedicationTab/CheckCondition/PillDummyData.swift
  APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
Labels: enhancement, 🐧 Jun

#60 [Feat] 메인약 추가페이지에서 텍스트필드 강조 기능 추가
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPill.storyboard
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift
Labels: enhancement, ⚡️ Cookie, 🐧 Jun

#58 [Feat] #26 - DiaryReadView 완성
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/CoreData/CoreDataManager.swift
  APillLog/APillLog/View/DiaryTab/CustomCellTableViewCell.swift
  APillLog/APillLog/View/DiaryTab/DiaryReadViewController.swift
  APillLog/APillLog/View/DiaryTab/DiaryView.storyboard
  APillLog/APillLog/View/DiaryTab/DiaryViewController.swift
Labels: enhancement, 👀 Dodo

#64 [Feat] #21, #62 - MedicationView의 TableView 데이터 연결
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/CoreData/CoreDataManager.swift
  APillLog/APillLog/View/MedicationTab/AddSecondaryPillView/AddSecondaryPillView.storyboard
  APillLog/APillLog/View/MedicationTab/AddSecondaryPillView/AddSecondaryPillViewController.swift
  APillLog/APillLog/View/MedicationTab/CustomCell/MedicationPillCell.swift
  APillLog/APillLog/View/MedicationTab/CustomCell/MedicationPillCell.xib
  APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingViewController.swift
  APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
Labels: enhancement, 💡 LED

#66 [Feat] #65 - 증상 입력 시 반환 값이 문자열이 아닌 배열로 반환
  APillLog/APillLog/View/MedicationTab/CheckCondition/CheckConditionViewController.swift
Labels: enhancement, 🐧 Jun, 🍔 Soi

#68 [Feat] #67 - 메인약 중복되는 입력 방지 기능 추가
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPill.storyboard
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift
  APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingViewController.swift
Labels: enhancement, 💡 LED

#69 [Feat] #26 #22 - DiaryView 수정
  APillLog/APillLog/CoreData/CoreDataManager.swift
  APillLog/APillLog/View/DiaryTab/DiaryReadViewController.swift
  APillLog/APillLog/View/DiaryTab/DiaryView.storyboard
  APillLog/APillLog/View/DiaryTab/DiaryViewController.swift
Labels: enhancement, 👀 Dodo

#71 [Feat] #70 - 서브약 추천 기능 구현
  APillLog/APillLog/CoreData/APillLog.xcdatamodeld/APillLog.xcdatamodel/contents
  APillLog/APillLog/CoreData/CoreDataManager.swift
  APillLog/APillLog/View/MedicationTab/AddSecondaryPillView/AddSecondaryPillViewController.swift
Labels: enhancement, 💡 LED

#72 [Fix] 함수오류수정
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/CoreData/APillLog.xcdatamodeld/APillLog.xcdatamodel/contents
  APillLog/APillLog/CoreData/CoreDataManager.swift
  APillLog/APillLog/CoreData/History+CoreDataClass.swift
  APillLog/APillLog/CoreData/History+CoreDataProperties.swift
  APillLog/APillLog/View/HistoryTab/HistoryViewController.swift
  APillLog/APillLog/View/MedicationTab/CustomCell/MedicationPillCell.swift
  APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
Labels: bug, ⚡️ Cookie

#74 [Fix] #59 Dynamic Height TableView
  APillLog/APillLog/CoreData/CoreDataManager.swift
  APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
Labels: bug

#80 [Fix] PrimaryPill 추가 시 발생하는 오류해결
  APillLog/APillLog/CoreData/APillLog.xcdatamodeld/APillLog.xcdatamodel/contents
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift
  APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingViewController.swift
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
Labels: bug, ⚡️ Cookie

#79 [Feat] HistoryView, CalendarView 완성
  APillLog/APillLog/Extentions/APillLog+Font.swift
  APillLog/APillLog/Utility/Calendar/CalendarView.swift
  APillLog/APillLog/Utility/Calendar/CalendarView.xib
  APillLog/APillLog/View/HistoryTab/HistoryTableViewCell.swift
  APillLog/APillLog/View/HistoryTab/HistoryView.storyboard
  APillLog/APillLog/View/HistoryTab/HistoryViewController.swift
Labels: enhancement

#91 [Feat] #87 - AddSecondaryPillView 레이아웃 수정
  APillLog/APillLog/View/MedicationTab/AddSecondaryPillView/AddSecondaryPillView.storyboard
  APillLog/APillLog/View/MedicationTab/AddSecondaryPillView/AddSecondaryPillViewController.swift
Labels: enhancement, 💡 LED

#92 [Feat] #85 CheckConditionView 기능/디자인 수정
  APillLog/APillLog/View/MedicationTab/CheckCondition/CheckConditionView.storyboard
  APillLog/APillLog/View/MedicationTab/CheckCondition/CheckConditionViewController.swift
Labels: enhancement, 🐧 Jun

#93 [Style] #86 - AddPrimaryPill placeholder 수정
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPill.storyboard
Labels: 💡 LED, style

#96 [FEAT] #89 DiaryView 디테일 수정
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/View/DiaryTab/DiaryView.storyboard
  APillLog/APillLog/View/DiaryTab/DiaryViewController.swift
  APillLog/APillLog/View/DiaryTab/DiaryWriteViewController.swift
Labels: enhancement, 👀 Dodo

#97 [Fix] #94 - Medication view/taking all pills button 임시 삭제
  APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
Labels: invalid

#99 [Feat] Calendar View 비어있을 때 수정
  APillLog/APillLog/View/HistoryTab/HistoryView.storyboard
  APillLog/APillLog/View/HistoryTab/HistoryViewController.swift
Labels: enhancement, 🍔 Soi

#101 [Fix] 다이어리뷰 텍스트 크기 변경, 탭바 수정
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/Application/AppDelegate.swift
  APillLog/APillLog/Info.plist
  APillLog/APillLog/View/Base.lproj/Main.storyboard
  APillLog/APillLog/View/DiaryTab/DiaryView.storyboard
Labels: bug, 👀 Dodo, style

#123 [Feat] 설정 페이지 연결
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/Application/AppDelegate.swift
  APillLog/APillLog/CoreData/CoreDataManager.swift
  APillLog/APillLog/View/Base.lproj/Main.storyboard
  APillLog/APillLog/View/PreferencesTab/AppVersionCheck/AppVersionCheck.swift
  APillLog/APillLog/View/PreferencesTab/Controller/LicenseController.swift
  APillLog/APillLog/View/PreferencesTab/Controller/QuestionViewController.swift
  APillLog/APillLog/View/PreferencesTab/Controller/ThanksToController.swift
  APillLog/APillLog/View/PreferencesTab/Controller/VersionController.swift
  APillLog/APillLog/View/PreferencesTab/PreferencesCustomCell/PreferencesCell.swift
  APillLog/APillLog/View/PreferencesTab/PreferencesCustomCell/PreferencesCell.xib
  APillLog/APillLog/View/PreferencesTab/PreferencesView.storyboard
  APillLog/APillLog/View/PreferencesTab/PreferencesViewController.swift
  APillLog/APillLog/View/PreferencesTab/PushNotificationView/PushNotificationController.swift
  APillLog/APillLog/View/PreferencesTab/PushNotificationView/PushNotificationView.storyboard
Labels: enhancement, ⚡️ Cookie

#117 [Feat] #113 - AddPrimaryPillView 피드백 반영
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPill.storyboard
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift
Labels: enhancement, 🐧 Jun

#116 [Feat] #84, #94, #108 - MedicationView 피드백 반영 및 ManageDosingView emptyCell 추가
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/CoreData/CoreDataManager.swift
  APillLog/APillLog/Utility/Calendar/CalendarView.xib
  APillLog/APillLog/View/MedicationTab/CheckCondition/CheckConditionView.storyboard
  APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingView.storyboard
  APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingViewController.swift
  APillLog/APillLog/View/MedicationTab/MedicationTabCustomCell/MedicationPillCell.swift
  APillLog/APillLog/View/MedicationTab/MedicationTabCustomCell/MedicationPillCell.xib
  APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
Labels: enhancement

#127 [Feat] 알림 설정 페이지, local push notification 구현
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/Extentions/UIView.swift
  APillLog/APillLog/View/PreferencesTab/Controller/LicenseView/LicenseController.swift
  APillLog/APillLog/View/PreferencesTab/Controller/LicenseView/LicenseView.storyboard
  APillLog/APillLog/View/PreferencesTab/Controller/QuestionsView/QuestionViewController.swift
  APillLog/APillLog/View/PreferencesTab/Controller/QuestionsView/QuestionsView.storyboard
  APillLog/APillLog/View/PreferencesTab/Controller/ThanksToView/ThanksToController.swift
  APillLog/APillLog/View/PreferencesTab/Controller/ThanksToView/ThanksToView.storyboard
  APillLog/APillLog/View/PreferencesTab/Controller/VersionView/VersionController.swift
  APillLog/APillLog/View/PreferencesTab/Controller/VersionView/VersionView.storyboard
  APillLog/APillLog/View/PreferencesTab/PreferencesView.storyboard
  APillLog/APillLog/View/PreferencesTab/PreferencesViewController.swift
  APillLog/APillLog/View/PreferencesTab/PushNotificationView/PushNotificationController.swift
  APillLog/APillLog/View/PreferencesTab/PushNotificationView/PushNotificationView.storyboard
Labels: enhancement, 🍔 Soi

#132 [Refactor] #131 - CoreDataManager 싱글톤 변환
  APillLog/APillLog/CoreData/CoreDataManager.swift
  APillLog/APillLog/View/DiaryTab/DiaryReadViewController.swift
  APillLog/APillLog/View/DiaryTab/DiaryViewController.swift
  APillLog/APillLog/View/DiaryTab/DiaryWriteViewController.swift
  APillLog/APillLog/View/HistoryTab/HistoryViewController.swift
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift
  APillLog/APillLog/View/MedicationTab/AddSecondaryPillView/AddSecondaryPillViewController.swift
  APillLog/APillLog/View/MedicationTab/CheckCondition/CheckConditionViewController.swift
  APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingViewController.swift
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
Labels: 💡 LED, Refactoring

#130 [Feat] 설정페이지 버전체크 페이지, 문의사항 페이지, 고마운 사람들 페이지 연결
  APillLog/APillLog/Extentions/APillLog+Font.swift
  APillLog/APillLog/Resources/Assets.xcassets/image/Apilllog.imageset/Contents.json
  APillLog/APillLog/Resources/Assets.xcassets/image/Apilllog.imageset/Group 280.svg
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift
  APillLog/APillLog/View/PreferencesTab/Controller/LicenseView/LicenseController.swift
  APillLog/APillLog/View/PreferencesTab/Controller/QuestionsView/QuestionViewController.swift
  APillLog/APillLog/View/PreferencesTab/Controller/QuestionsView/QuestionsView.storyboard
  APillLog/APillLog/View/PreferencesTab/Controller/ThanksToView/ThanksToController.swift
  APillLog/APillLog/View/PreferencesTab/Controller/ThanksToView/ThanksToView.storyboard
  APillLog/APillLog/View/PreferencesTab/Controller/VersionView/VersionController.swift
  APillLog/APillLog/View/PreferencesTab/Controller/VersionView/VersionView.storyboard
  APillLog/APillLog/View/PreferencesTab/PreferencesView.storyboard
  APillLog/APillLog/View/PreferencesTab/PreferencesViewController.swift
Labels: enhancement, ⚡️ Cookie

#135 [Feat] #119 - 환경 설정 탭 레이아웃 및 함수 구현
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/View/PreferencesTab/PreferencesCustomCell/PreferencesCell.swift
  APillLog/APillLog/View/PreferencesTab/PreferencesCustomCell/PreferencesCell.xib
  APillLog/APillLog/View/PreferencesTab/PreferencesView.storyboard
  APillLog/APillLog/View/PreferencesTab/PreferencesViewController.swift
Labels: enhancement, 🐧 Jun

#139 [Fix] 컴플릭해결
  APillLog/APillLog/View/PreferencesTab/Controller/QuestionsView/QuestionViewController.swift
  APillLog/APillLog/View/PreferencesTab/PreferencesView.storyboard
  APillLog/APillLog/View/PreferencesTab/PreferencesViewController.swift
Labels: bug, ⚡️ Cookie, 🐧 Jun

#134 [Feat] 알람 설정 뷰 수정
  APillLog/APillLog/Application/AppDelegate.swift
  APillLog/APillLog/View/PreferencesTab/PushNotificationView/PushNotificationController.swift
  APillLog/APillLog/View/PreferencesTab/PushNotificationView/PushNotificationView.storyboard
Labels: enhancement, 🍔 Soi

#137 [Feat] #129 - CheckConditionView 피드백 수정
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/View/MedicationTab/CheckCondition/CheckConditionView.storyboard
  APillLog/APillLog/View/MedicationTab/CheckCondition/CheckConditionViewController.swift
  APillLog/APillLog/View/MedicationTab/CheckCondition/PillDummyData.swift
Labels: enhancement, 🐧 Jun

#145 [Feat, Fix] #77 #94 MedicationView Chores
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/CoreData/CoreDataManager.swift
  APillLog/APillLog/View/MedicationTab/MedicationTabCustomCell/MedicationPillCell.swift
  APillLog/APillLog/View/MedicationTab/MedicationTabCustomCell/MedicationPillCell.xib
  APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
Labels: enhancement

#156 [Fix] 저녁 시간 저장 안 되는 문제 해결
  APillLog/APillLog/View/Base.lproj/LaunchScreen.storyboard
  APillLog/APillLog/View/PreferencesTab/PushNotificationView/PushNotificationController.swift
Labels: bug, 🍔 Soi

#159 [Feat] FSCalendar 구현
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/Extentions/APillLog+Font.swift
  APillLog/APillLog/View/FSCalendarView/FSCalendarView.storyboard
  APillLog/APillLog/View/FSCalendarView/FSCalendarViewController.swift
  APillLog/APillLog/View/HistoryTab/HistoryView.storyboard
Labels: enhancement, 🐧 Jun

#154 [Feat] #155 토글에 따른 PrimaryPill 불러오기
  APillLog/APillLog/CoreData/CoreDataManager.swift
Labels: enhancement, ⚡️ Cookie
