Repository DeveloperAcademy-POSTECH/MC3-Team2-APillog, pull requests merged in 2022-08, with the labels that each got.

#164 [Feat] 복용률 보이는 방법 수정
  APillLog/APillLog/CoreData/CoreDataManager.swift
Labels: bug, 🍔 Soi

#167 [Feat] 복용 관리 페이지 디자인 수정
  APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingView.storyboard
Labels: 🍔 Soi, style

#170 [Feat] 추가약 모달 뷰 수정
  APillLog/APillLog/View/MedicationTab/AddSecondaryPillView/AddSecondaryPillView.storyboard
  APillLog/APillLog/View/MedicationTab/AddSecondaryPillView/AddSecondaryPillViewController.swift
Labels: 🍔 Soi, style

#173 [Feat] Calendar View - History View 통합 / AddPrimaryPill View 취소-저장 버튼 색상 수정
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/CoreData/CoreDataManager.swift
  APillLog/APillLog/Extentions/APillLog+Color.swift
  APillLog/APillLog/Extentions/APillLog+Font.swift
  APillLog/APillLog/Resources/Assets.xcassets/AColorPalette/ACalendarDetail.colorset/Contents.json
  APillLog/APillLog/Resources/Assets.xcassets/AColorPalette/ACalendarPill.colorset/Contents.json
  APillLog/APillLog/Resources/Assets.xcassets/AColorPalette/ACalendarSide.colorset/Contents.json
  APillLog/APillLog/View/Base.lproj/Main.storyboard
  APillLog/APillLog/View/FSCalendarView/FSCalendarView.storyboard
  APillLog/APillLog/View/FSCalendarView/FSCalendarViewController.swift
  APillLog/APillLog/View/HistoryTab/HistoryDetail/HistoryDetailView.storyboard
  APillLog/APillLog/View/HistoryTab/HistoryDetail/HistoryDetailViewController.swift
  APillLog/APillLog/View/HistoryTab/HistoryView.storyboard
  APillLog/APillLog/View/HistoryTab/HistoryViewController.swift
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPill.storyboard
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift
Labels: enhancement, 🐧 Jun

#171 [Feat] MedicationView, ManageDosingView 피드백 반영 레이아웃 및 기능 수정
  APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
Labels: enhancement, 💡 LED, style

#138 [Feat] WatchOS 기능 구현
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/CoreData/CoreDataManager.swift
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift
  APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingViewController.swift
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
  APillLog/APillLog/WatchConnection/ConnectionModelPhone.swift
  APillLog/ApillLogWatch WatchKit Extension/APillLogApp.swift
  APillLog/ApillLogWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Circular.imageset/Contents.json
  APillLog/ApillLogWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Contents.json
  APillLog/ApillLogWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Extra Large.imageset/Contents.json
  APillLog/ApillLogWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Graphic Bezel.imageset/Contents.json
  APillLog/ApillLogWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Graphic Circular.imageset/Contents.json
  APillLog/ApillLogWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Graphic Corner.imageset/Contents.json
  APillLog/ApillLogWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Graphic Extra Large.imageset/Contents.json
  APillLog/ApillLogWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Graphic Large Rectangular.imageset/Contents.json
  APillLog/ApillLogWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Modular.imageset/Contents.json
  APillLog/ApillLogWatch WatchKit Extension/Assets.xcassets/Complication.complicationset/Utilitarian.imageset/Contents.json
  APillLog/ApillLogWatch WatchKit Extension/Assets.xcassets/Contents.json
  APillLog/ApillLogWatch WatchKit Extension/CheckConditionView.swift
  APillLog/ApillLogWatch WatchKit Extension/ComplicationController.swift
  APillLog/ApillLogWatch WatchKit Extension/ConnectionModelWatch.swift
  APillLog/ApillLogWatch WatchKit Extension/ContentView.swift
  APillLog/ApillLogWatch WatchKit Extension/Info.plist
  APillLog/ApillLogWatch WatchKit Extension/NotificationController.swift
  APillLog/ApillLogWatch WatchKit Extension/NotificationView.swift
  APillLog/ApillLogWatch WatchKit Extension/Preview Content/Preview Assets.xcassets/Contents.json
  APillLog/ApillLogWatch WatchKit Extension/PushNotificationPayload.apns
  APillLog/ApillLogWatch WatchKit Extension/RecordPrimaryPillView.swift
  APillLog/ApillLogWatch/Assets.xcassets/AccentColor.colorset/Contents.json
  APillLog/ApillLogWatch/Assets.xcassets/AppIcon.appiconset/100.png
  APillLog/ApillLogWatch/Assets.xcassets/AppIcon.appiconset/102.png
  APillLog/ApillLogWatch/Assets.xcassets/AppIcon.appiconset/1024.png
  APillLog/ApillLogWatch/Assets.xcassets/AppIcon.appiconset/172.png
  APillLog/ApillLogWatch/Assets.xcassets/AppIcon.appiconset/196.png
  APillLog/ApillLogWatch/Assets.xcassets/AppIcon.appiconset/216.png
  APillLog/ApillLogWatch/Assets.xcassets/AppIcon.appiconset/234.png
  APillLog/ApillLogWatch/Assets.xcassets/AppIcon.appiconset/48.png
  APillLog/ApillLogWatch/Assets.xcassets/AppIcon.appiconset/55.png
  APillLog/ApillLogWatch/Assets.xcassets/AppIcon.appiconset/58.png
  APillLog/ApillLogWatch/Assets.xcassets/AppIcon.appiconset/66.png
  APillLog/ApillLogWatch/Assets.xcassets/AppIcon.appiconset/80.png
  APillLog/ApillLogWatch/Assets.xcassets/AppIcon.appiconset/87.png
  APillLog/ApillLogWatch/Assets.xcassets/AppIcon.appiconset/88.png
  APillLog/ApillLogWatch/Assets.xcassets/AppIcon.appiconset/92.png
  APillLog/ApillLogWatch/Assets.xcassets/AppIcon.appiconset/Contents.json
  APillLog/ApillLogWatch/Assets.xcassets/Contents.json
  APillLog/Pods/Pods.xcodeproj/project.pbxproj
Labels: enhancement, invalid, 💡 LED

#176 [Feat/Style] 수정 사항 적용
  APillLog/APillLog/CoreData/CoreDataManager.swift
  APillLog/APillLog/View/DiaryTab/DiaryView.storyboard
  APillLog/APillLog/View/FSCalendarView/FSCalendarViewController.swift
  APillLog/APillLog/View/HistoryTab/HistoryDetail/HistoryDetailChartView/HistoryDetailChartView.swift
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPill.storyboard
  APillLog/APillLog/View/MedicationTab/CheckCondition/CheckConditionView.storyboard
  APillLog/APillLog/View/MedicationTab/CheckCondition/CheckConditionViewController.swift
  APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingView.storyboard
  APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingViewController.swift
  APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
  APillLog/APillLog/View/PreferencesTab/Controller/LicenseView/LicenseController.swift
  APillLog/APillLog/View/PreferencesTab/Controller/LicenseView/LicenseDetailView/ChartsLicenseView.storyboard
  APillLog/APillLog/View/PreferencesTab/Controller/LicenseView/LicenseDetailView/ChartsLicenseViewController.swift
  APillLog/APillLog/View/PreferencesTab/Controller/LicenseView/LicenseDetailView/FSLicenseView.storyboard
  APillLog/APillLog/View/PreferencesTab/Controller/LicenseView/LicenseDetailView/FSLicenseViewController.swift
  APillLog/APillLog/View/PreferencesTab/Controller/QuestionsView/QuestionViewController.swift
  APillLog/APillLog/View/PreferencesTab/Controller/ThanksToView/ThanksToController.swift
  APillLog/APillLog/View/PreferencesTab/Controller/VersionView/VersionController.swift
  APillLog/APillLog/View/PreferencesTab/PreferencesView.storyboard
  APillLog/APillLog/View/PreferencesTab/PushNotificationView/PushNotificationController.swift
Labels: enhancement, ⚡️ Cookie, 🐧 Jun, 🍔 Soi, style

#177 [Feat] History Detail view 수정
  APillLog/APillLog/View/HistoryTab/HistoryDetail/HistoryDetailView.storyboard
  APillLog/APillLog/View/HistoryTab/HistoryDetail/HistoryDetailViewController.swift
Labels: enhancement, 🍔 Soi

#178 [Fix] ThanksTo View Auto Layout 수정
  APillLog/APillLog/View/PreferencesTab/Controller/ThanksToView/ThanksToView.storyboard
Labels: ⚡️ Cookie, 🐧 Jun, style

#203 [Feat] # 189 , # 185 - 다이어리뷰 수정 , 앱 이름 변경
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/Utility/Calendar/CalendarMonth.swift
  APillLog/APillLog/Utility/Calendar/CalendarMonthView.xib
  APillLog/APillLog/View/DiaryTab/CustomCellTableViewCell.swift
  APillLog/APillLog/View/DiaryTab/DiaryEditViewController.swift
  APillLog/APillLog/View/DiaryTab/DiaryReadViewController.swift
  APillLog/APillLog/View/DiaryTab/DiaryStorageViewController.swift
  APillLog/APillLog/View/DiaryTab/DiaryView.storyboard
  APillLog/APillLog/View/DiaryTab/DiaryViewController.swift
  APillLog/APillLog/View/DiaryTab/DiaryWriteViewController.swift
  APillLog/APillLog/View/DiaryTab/DiaryWriteViewController2.swift
  APillLog/APillLog/View/DiaryTab/DiaryWriteViewController3.swift
  APillLog/APillLog/View/DiaryTab/MyCustomHeader.swift
  APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
Labels: bug, enhancement, 👀 Dodo, sprint3

#200 [Fix] SettingView 탭바 아이템 이름변경 버그 수정
  APillLog/APillLog/View/Base.lproj/Main.storyboard
  APillLog/APillLog/View/PreferencesTab/Controller/LicenseView/LicenseController.swift
Labels: bug, ⚡️ Cookie

#201 [Feat] 리포트 뷰 기간 설정 기능 구현
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/CoreData/CoreDataManager.swift
  APillLog/APillLog/Extentions/UIView.swift
  APillLog/APillLog/View/HistoryTab/HistoryDetail/DIYCalendarCell.swift
  APillLog/APillLog/View/HistoryTab/HistoryDetail/HistoryDetailChartView/HistoryDetailChartView.swift
  APillLog/APillLog/View/HistoryTab/HistoryDetail/HistoryDetailView.storyboard
  APillLog/APillLog/View/HistoryTab/HistoryDetail/HistoryDetailViewController.swift
Labels: enhancement, 🍔 Soi

#198 [Feat] HistoryDetailView 차트 디자인 수정
  APillLog/APillLog/View/HistoryTab/HistoryDetail/HistoryDetailChartView/HistoryDetailChartView.swift
  APillLog/APillLog/View/HistoryTab/HistoryDetail/HistoryDetailChartView/HistoryDetailChartView.xib
  APillLog/Pods/Charts/Source/Charts/Renderers/BarChartRenderer.swift
Labels: enhancement, 💡 LED

#208 AddPrimaryPillView / 메인 약 추가 DropDown 설정 - Sprint3 수정 사항 반영
  APillLog/APillLog/Extentions/APillLog+Color.swift
  APillLog/APillLog/Resources/Assets.xcassets/AColorPalette/ABorder.colorset/Contents.json
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPill.storyboard
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/PrimaryPillDosingCycleChipButton.swift
  APillLog/Podfile
  APillLog/Podfile.lock
  APillLog/Pods/DropDown/DropDown/helpers/DPDConstants.swift
  APillLog/Pods/DropDown/DropDown/helpers/DPDKeyboardListener.swift
  APillLog/Pods/DropDown/DropDown/helpers/DPDUIView+Extension.swift
  APillLog/Pods/DropDown/DropDown/resources/DropDownCell.xib
  APillLog/Pods/DropDown/DropDown/src/DropDown+Appearance.swift
  APillLog/Pods/DropDown/DropDown/src/DropDown.swift
  APillLog/Pods/DropDown/DropDown/src/DropDownCell.swift
  APillLog/Pods/DropDown/LICENSE
  APillLog/Pods/DropDown/README.md
  APillLog/Pods/Manifest.lock
  APillLog/Pods/Pods.xcodeproj/project.pbxproj
  APillLog/Pods/Target Support Files/DropDown/DropDown-Info.plist
  APillLog/Pods/Target Support Files/DropDown/DropDown-dummy.m
  APillLog/Pods/Target Support Files/DropDown/DropDown-prefix.pch
  APillLog/Pods/Target Support Files/DropDown/DropDown-umbrella.h
  APillLog/Pods/Target Support Files/DropDown/DropDown.debug.xcconfig
  APillLog/Pods/Target Support Files/DropDown/DropDown.modulemap
  APillLog/Pods/Target Support Files/DropDown/DropDown.release.xcconfig
  APillLog/Pods/Target Support Files/Pods-APillLog/Pods-APillLog-acknowledgements.markdown
  APillLog/Pods/Target Support Files/Pods-APillLog/Pods-APillLog-acknowledgements.plist
  APillLog/Pods/Target Support Files/Pods-APillLog/Pods-APillLog-frameworks-Debug-input-files.xcfilelist
  APillLog/Pods/Target Support Files/Pods-APillLog/Pods-APillLog-frameworks-Debug-output-files.xcfilelist
  APillLog/Pods/Target Support Files/Pods-APillLog/Pods-APillLog-frameworks-Release-input-files.xcfilelist
  APillLog/Pods/Target Support Files/Pods-APillLog/Pods-APillLog-frameworks-Release-output-files.xcfilelist
  APillLog/Pods/Target Support Files/Pods-APillLog/Pods-APillLog-frameworks.sh
  APillLog/Pods/Target Support Files/Pods-APillLog/Pods-APillLog.debug.xcconfig
  APillLog/Pods/Target Support Files/Pods-APillLog/Pods-APillLog.release.xcconfig
Labels: enhancement, 🐧 Jun, style

#209 [Feat] 이전 날짜에서 추가약 등록이 가능하도록 변경
  APillLog/APillLog/View/MedicationTab/AddSecondaryPillView/AddSecondaryPillViewController.swift
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
Labels: enhancement, ⚡️ Cookie

#196 [Feat] WatchOS 개별 약 복용 기능 구현
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/CoreData/CoreDataManager.swift
  APillLog/APillLog/Info.plist
  APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingViewController.swift
  APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
  APillLog/APillLog/WatchConnection/ConnectionModelPhone.swift
  APillLog/ApillLogWatch WatchKit Extension/APillLogApp.swift
  APillLog/ApillLogWatch WatchKit Extension/ConnectionModelWatch.swift
  APillLog/ApillLogWatch WatchKit Extension/ContentView.swift
  APillLog/ApillLogWatch WatchKit Extension/RecordPrimaryPillView.swift
Labels: enhancement, 💡 LED

#210 [Fix] Main view 수정 반영 #184, #205
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/View/MedicationTab/EditTimeModal/EditTimeModalView.storyboard
  APillLog/APillLog/View/MedicationTab/EditTimeModal/EditTimeModalViewController.swift
  APillLog/APillLog/View/MedicationTab/MedicationTabCustomCell/MedicationPillCell.swift
  APillLog/APillLog/View/MedicationTab/MedicationTabCustomCell/MedicationPillCell.xib
  APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
Labels: enhancement, 🍒 Yeni

#219 [Fix] #214 - 추가약 삭제 오류
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
Labels: bug, ⚡️ Cookie

#223 [Feat] #217, 186 - 메인 약 직접 추가 및 HistoryDetailView 스와이프 제한
  APillLog/APillLog/View/HistoryTab/HistoryDetail/HistoryDetailViewController.swift
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPill.storyboard
  APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
Labels: enhancement, 🐧 Jun, style

#224 [Feat] Onboarding 구현
  APillLog/APillLog.xcodeproj/project.pbxproj
  APillLog/APillLog/Application/AppDelegate.swift
  APillLog/APillLog/Application/SceneDelegate.swift
  APillLog/APillLog/Resources/Assets.xcassets/onboardingImage/Contents.json
  APillLog/APillLog/Resources/Assets.xcassets/onboardingImage/onboarding1.imageset/Contents.json
  APillLog/APillLog/Resources/Assets.xcassets/onboardingImage/onboarding1.imageset/onboarding1.png
  APillLog/APillLog/Resources/Assets.xcassets/onboardingImage/onboarding2.imageset/Contents.json
  APillLog/APillLog/Resources/Assets.xcassets/onboardingImage/onboarding2.imageset/onboarding2.png
  APillLog/APillLog/Resources/Assets.xcassets/onboardingImage/onboarding3.imageset/Contents.json
  APillLog/APillLog/Resources/Assets.xcassets/onboardingImage/onboarding3.imageset/onboarding3.png
  APillLog/APillLog/Resources/Assets.xcassets/onboardingImage/onboarding4.imageset/Contents.json
  APillLog/APillLog/Resources/Assets.xcassets/onboardingImage/onboarding4.imageset/onboarding4.png
  APillLog/APillLog/Resources/Assets.xcassets/onboardingImage/onboarding5.imageset/Contents.json
  APillLog/APillLog/Resources/Assets.xcassets/onboardingImage/onboarding5.imageset/onboarding5.png
  APillLog/APillLog/Resources/Assets.xcassets/onboardingImage/onboarding6.imageset/Contents.json
  APillLog/APillLog/Resources/Assets.xcassets/onboardingImage/onboarding6.imageset/onboarding6.png
  APillLog/APillLog/Resources/Assets.xcassets/onboardingImage/onboarding7.imageset/Contents.json
  APillLog/APillLog/Resources/Assets.xcassets/onboardingImage/onboarding7.imageset/onboarding7.png
  APillLog/APillLog/View/Base.lproj/Main.storyboard
  APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
  APillLog/APillLog/View/Onboarding/Onboarding.storyboard
  APillLog/APillLog/View/Onboarding/OnboardingCollectionViewCell.swift
  APillLog/APillLog/View/Onboarding/OnboardingSlide.swift
  APillLog/APillLog/View/Onboarding/OnboardingViewController.swift
Labels: enhancement, 🍔 Soi
